In [3]:
import numpy as np

In [6]:
arr = [1,2,3,4,5,6,7,8,9,10]
arr = np.array(arr)


In [7]:
arr.ndim #Know about dimesion

1

In [11]:
arr.shape  #know about rows and columns

(10,)

In [12]:
arr.dtype #know about datatypes

dtype('int64')

In [13]:
arr.size # Know about size

10

<br>

### **Creating 'N' Dimensional Array**

In [16]:
oneD_array = np.array([1,2,3,4,5,6])
oneD_array.shape

(6,)

In [17]:
twoD_array = np.array([[1,2,3,4], [5,6,7,8]])
twoD_array.shape

(2, 4)

In [20]:
threeD_array = np.array([[[1,2], [3,4], [5,6]]])
threeD_array.shape

(1, 3, 2)

<br>

### **Matrix Multiplication**

In [25]:
mat1 = np.array([[1,2,3,4], [5,6,7,8]])
mat2 = np.array([[4,5], [6,5], [5,9], [1,3]])


array([[ 35,  54],
       [ 99, 142]])

In [26]:
# Method 1

mat3 = mat1 @ mat2
print(mat3)

[[ 35  54]
 [ 99 142]]


In [28]:
# Method 2

mat3  = np.matmul(mat1, mat2)
print(mat3)

[[ 35  54]
 [ 99 142]]


In [29]:
# Method 3
mat3 = np.dot(mat1,mat2)
print(mat3)

[[ 35  54]
 [ 99 142]]


<br>

**Deep Copy vs Shallow Copy**

In [46]:
array = [2,4,656,546,12,2,9,54]
array = np.array(array)

In [47]:
# Shallow Copy

arr2 = array.view()
arr2

array([  2,   4, 656, 546,  12,   2,   9,  54])

In [48]:
arr2[5] = 909
print(arr2)
print(array)

[  2   4 656 546  12 909   9  54]
[  2   4 656 546  12 909   9  54]


In [49]:
deep_arr = array.copy()
deep_arr

array([  2,   4, 656, 546,  12, 909,   9,  54])

In [50]:
deep_arr[3]= 0
print(deep_arr)
print(array)

[  2   4 656   0  12 909   9  54]
[  2   4 656 546  12 909   9  54]


<br>


**Array creation from function**

In [52]:
array =  np.fromfunction(lambda i,j :  i==j, (3,3))
array

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [56]:
text = '1,2,3,4,5,6,7,8'
array = np.fromstring(text, sep=',', dtype=int)
array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
array =  np.fromiter([1,2,3,4], dtype=float)
array

array([1., 2., 3., 4.])

In [64]:
arr= [1,2,34]
arr = np.array(arr)

copy1 = np.array(arr)
print(copy1)

copy2 = np.asarray(arr)
print(copy2)

print(copy1.__add__)
print(copy2.__add__)
print(arr.__add__)

[ 1  2 34]
[ 1  2 34]
<method-wrapper '__add__' of numpy.ndarray object at 0x7aaec448bed0>
<method-wrapper '__add__' of numpy.ndarray object at 0x7aaec448ba50>
<method-wrapper '__add__' of numpy.ndarray object at 0x7aaec448ba50>


<br>

**Creating Sequence**

In [65]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [66]:
np.linspace(10, 100, 10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [68]:
np.logspace(1, 3, 3)

array([  10.,  100., 1000.])

<br>

**Filter Array**

In [74]:
arr = np.array([1,2,3,4,5,6,7,8])
arr[arr%2==0]

array([2, 4, 6, 8])

In [76]:
arr =  np.array([[10,20], [30,40]])
arr+10

array([[20, 30],
       [40, 50]])

<br>

**Array Manipulation**

In [78]:
arr = np.array([[10,3,2], [43,3,199], [6,9,100]])

In [79]:
arr

array([[ 10,   3,   2],
       [ 43,   3, 199],
       [  6,   9, 100]])

In [82]:
flatten_array = arr.flatten()
print(flatten_array)

[ 10   3   2  43   3 199   6   9 100]


In [86]:
expand_dim = arr.copy()
np.expand_dims(expand_dim, axis=1)

array([[[ 10,   3,   2]],

       [[ 43,   3, 199]],

       [[  6,   9, 100]]])

In [89]:
squeez = arr.copy()
 np.squeeze(squeez)


array([[ 10,   3,   2],
       [ 43,   3, 199],
       [  6,   9, 100]])

In [90]:
roll_array = np.array([3,66,23,78,956,87])
np.roll(roll_array, 2)


array([956,  87,   3,  66,  23,  78])

<br>

**Sorting**

In [94]:
arr = np.array([6,11,23,4,87,645,32,43,54,9])

print(np.sort(arr))
arr.sort()
print(np.searchsorted(arr, 0))

[  4   6   9  11  23  32  43  54  87 645]
0
