In [126]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV


In [87]:
data = load_iris()

In [88]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [89]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [90]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [91]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [92]:
df = pd.DataFrame(data.data, columns = data.feature_names)
df['target'] = data.target

# To make it binary classification

df = df[df['target']!= 2]



In [93]:
df['target'].value_counts()

target
0    50
1    50
Name: count, dtype: int64

In [94]:
df.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [95]:
df.describe()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)      target
count         100.000000        100.000000  ...        100.000000  100.000000
mean            5.471000          3.099000  ...          0.786000    0.500000
std             0.641698          0.478739  ...          0.565153    0.502519
min             4.300000          2.000000  ...          0.100000    0.000000
25%             5.000000          2.800000  ...          0.200000    0.000000
50%             5.400000          3.050000  ...          0.800000    0.500000
75%             5.900000          3.400000  ...          1.300000    1.000000
max             7.000000          4.400000  ...          1.800000    1.000000

[8 rows x 5 columns]

<br>

**Splitting Independent and Dependent Features**

In [96]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [97]:
X.head(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2

In [98]:
y.head(2)

0    0
1    0
Name: target, dtype: int64

**Train Test Split**

In [99]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state=10)

 X_train.shape, X_test.shape, y_train.shape, y_test.shape

((85, 4), (15, 4), (85,), (15,))

In [101]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test =  scaler.transform(X_test)

<br>

**Logistic Regression**

In [106]:
classifier = LogisticRegression()

In [107]:
classifier.fit(X_train, y_train)

LogisticRegression()

In [108]:
y_pred = classifier.predict(X_test)

In [109]:
y_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1])

<br>

**Confusion matrix,accuracy score,classification report**

In [113]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[9 0]
 [0 6]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00         6

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



<br>

**Hyperparameter Tuning**

In [122]:
parameters={'penalty':('l1','l2','elasticnet',None),'C':[1,10,20]}

clf = GridSearchCV(classifier, param_grid = parameters, cv=5)

clf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [123]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [124]:
classifier=LogisticRegression(C=1,penalty='l2')

In [125]:
classifier.fit(X_train,y_train)

y_pred=classifier.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[9 0]
 [0 6]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00         6

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



<br>

**Randomized Search**

In [128]:
random_clf=RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5)

In [129]:
random_clf.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [130]:
random_clf.best_params_

{'penalty': 'l2', 'C': 10}

In [ ]:
classifier=LogisticRegression(C=10,penalty='l2')

In [131]:
classifier.fit(X_train,y_train)

y_pred=classifier.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[9 0]
 [0 6]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00         6

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

